experiment: generation_mcvsr
description: Test the DuSR-RealV2-Paired L1 model on RealMCVSR-Real.

test:
  module: tools.test_sr
  arguments:
    dataset_root: ${DATASET_ROOT}
    dataset_name: RealMCVSR-Real
    dataset_type: external
    coordinates: ${PROJECT_ROOT}/coordinates/RealMCVSR-Real.json
    model_variant: v3
    checkpoint: ${PROJECT_ROOT}/weights/pretrained/DuSRFlow_DuSR-RealV2-Paired_L1.pth
    result_dir: ${RESULT_ROOT}/generation
    run_name: Paired_L1
    save_images: true
